// ESLint flat config (ESLint 9+).
//
// This codebase is deliberately NOT split into ES modules — the 21 files
// in src/js/ are concatenated at build time (see build.js) into one
// global-scope script, exactly like the original single-file app. That
// means every function/variable defined in any file is callable from any
// other file, same as before the split.
//
// ESLint lints each file in isolation by default, so without help it
// would flag every cross-file reference as "no-undef" (undefined
// variable) — which would be both wrong and enormously noisy. The
// "appGlobals" block below tells ESLint about every name this app defines
// across all its files, so no-undef only fires on the bugs it's actually
// meant to catch: genuine typos and dangling references — exactly the
// class of bug (mismatched function names, stale element IDs) that's
// caused real problems in this codebase before.
//
// Regenerate this list after adding/removing top-level functions or vars:
//   grep -ohE '^(async )?function ([A-Za-z0-9_]+)' src/js/*.js
//   grep -ohE '^(var|let|const) ([A-Za-z0-9_]+)' src/js/*.js

const appGlobals = {
    "BACKUP_REMINDER_THRESHOLD": "writable",
    "BRAND_LABELS": "writable",
    "BRAND_PRICES": "writable",
    "BRAND_WEBSITES": "writable",
    "BRUSH_UNDO_MAX": "writable",
    "BRUSH_WET_DOWNSCALE": "writable",
    "BRUSH_WET_MS": "writable",
    "COLORS": "writable",
    "DILUTION_STOPS": "writable",
    "GRAN_TILE_SIZE": "writable",
    "GROUP_LABELS": "writable",
    "GROUP_ORDER": "writable",
    "HARMONY_TYPES": "writable",
    "LF_LABELS": "writable",
    "MIX_RECIPES": "writable",
    "NONSTAINING_PIGMENT_FAMILIES": "writable",
    "PAGE_META": "writable",
    "PREMIUM_PIGMENTS": "writable",
    "PROMPT_DATA": "writable",
    "RECOMMENDED_PALETTES": "writable",
    "STAINING_LABELS": "writable",
    "STAINING_PIGMENT_FAMILIES": "writable",
    "SWIPE_COMMIT_PX": "writable",
    "SWIPE_REVEAL_PX": "writable",
    "TRANSPARENCY_LABELS": "writable",
    "VS_MASTERS_WATERCOLOR": "writable",
    "VS_ZONE_LABELS": "writable",
    "_P": "writable",
    "_brush": "writable",
    "_brushSmoothstep": "writable",
    "_chipCurrentPalId": "writable",
    "_dragModeCard": "writable",
    "_drainQ": "writable",
    "_granTile": "writable",
    "_kMixChannelNum": "writable",
    "_ks": "writable",
    "_ksR": "writable",
    "_linToSrgb": "writable",
    "_origShowPage": "writable",
    "_renderQ": "writable",
    "_srgbToLin": "writable",
    "_swipeState": "writable",
    "_toastTimer": "writable",
    "_vsMasterBag": "writable",
    "_vsPromptRolledOnce": "writable",
    "_vsScaleChartBuilt": "writable",
    "activePaletteId": "writable",
    "activePaletteView": "writable",
    "activeRecipeTag": "writable",
    "addColorToPalette": "writable",
    "addSolverMixToPalette": "writable",
    "allRecipeTags": "writable",
    "applyImport": "writable",
    "attachBrushPointerEvents": "writable",
    "backupJSON": "writable",
    "brushState": "writable",
    "brushWetnessAt": "writable",
    "buildBackupObject": "writable",
    "chipAddToPalette": "writable",
    "chroma": "writable",
    "clearBrushCanvas": "writable",
    "clearQ": "writable",
    "closeDilutionModal": "writable",
    "closeMobileDrawer": "writable",
    "closeModal": "writable",
    "closeNavMore": "writable",
    "closeSidebars": "writable",
    "closeSwipeRow": "writable",
    "commitSwipeDelete": "writable",
    "confirmAddMix": "writable",
    "copyBackupToClipboard": "writable",
    "createPalette": "writable",
    "currentPrompt": "writable",
    "debounce": "writable",
    "debouncedRenderOpacity": "writable",
    "debouncedRenderPigment": "writable",
    "debouncedRenderRecipes": "writable",
    "debouncedRenderRef": "writable",
    "debouncedRenderShopGrid": "writable",
    "deletePalette": "writable",
    "deltaE": "writable",
    "deltaELabel": "writable",
    "dismissBackupReminder": "writable",
    "dismissBanner": "writable",
    "downloadBackup": "writable",
    "downloadValueStudy": "writable",
    "dragPalId": "writable",
    "dragSrcIdx": "writable",
    "drawerOpen": "writable",
    "duplicatePalette": "writable",
    "editAppName": "writable",
    "enterDragMode": "writable",
    "estimateDryShift": "writable",
    "estimateStaining": "writable",
    "exitDragMode": "writable",
    "exportCurrentPalette": "writable",
    "extractDominantColors": "writable",
    "fade": "writable",
    "fbm": "writable",
    "fbmAniso": "writable",
    "findClosestColor": "writable",
    "findColorMatches": "writable",
    "genId": "writable",
    "getRefFiltered": "writable",
    "getSortedColors": "writable",
    "getTubeKey": "writable",
    "getTubeLevel": "writable",
    "goToBackupPage": "writable",
    "granTileValue": "writable",
    "handleImportFile": "writable",
    "hapticSuccess": "writable",
    "hapticTap": "writable",
    "hapticWarning": "writable",
    "harmonyColor": "writable",
    "harmonyPalId": "writable",
    "harmonyType": "writable",
    "hashScore": "writable",
    "hexToHsl": "writable",
    "hexToHslSort": "writable",
    "hexToLab": "writable",
    "hslToHex": "writable",
    "importFromTextarea": "writable",
    "initBrushCanvas": "writable",
    "initDragDrop": "writable",
    "initSwipeRows": "writable",
    "isMobile": "writable",
    "isPremium": "writable",
    "lastMatchTargetHex": "writable",
    "lerp": "writable",
    "loadBrushColor": "writable",
    "loadPalettes": "writable",
    "loadRecommendedPalette": "writable",
    "loadShoppingList": "writable",
    "loadTubeData": "writable",
    "loadValueStudyImage": "writable",
    "markBackupDone": "writable",
    "markBrushWet": "writable",
    "mixHex": "writable",
    "mixModeActive": "writable",
    "mixPaint": "writable",
    "mixPaintN": "writable",
    "mixSelectedIdxs": "writable",
    "mixingSubView": "writable",
    "mobileNavDrawer": "writable",
    "mudInfo": "writable",
    "noise2": "writable",
    "onMatchColorPick": "writable",
    "onMatchHexTyped": "writable",
    "onSwipeEnd": "writable",
    "onSwipeMove": "writable",
    "onSwipeStart": "writable",
    "opacityBrandFilter": "writable",
    "opacityScore": "writable",
    "openDilutionModal": "writable",
    "openMobileDrawer": "writable",
    "openNewPaletteModal": "writable",
    "openRefChip": "writable",
    "openSwipeRow": "writable",
    "paintBrushDab": "writable",
    "paintBrushPaperBase": "writable",
    "paintSwatchRegion": "writable",
    "palSortMode": "writable",
    "paletteDarkestReach": "writable",
    "paletteOptionsHtml": "writable",
    "palettes": "writable",
    "parseHex": "writable",
    "photoDarkestLuminance": "writable",
    "populateChipModal": "writable",
    "populateCostSelect": "writable",
    "populateTrackerSelect": "writable",
    "populateVsSuggestSelect": "writable",
    "posterizeValueStudy": "writable",
    "promptBags": "writable",
    "promptLastPicked": "writable",
    "pushBrushUndoSnapshot": "writable",
    "queueRender": "writable",
    "redrawValueStudy": "writable",
    "refBrand": "writable",
    "removeFromPalette": "writable",
    "removeSwatchPhoto": "writable",
    "renamePalette": "writable",
    "renderBackupPage": "writable",
    "renderBrushTray": "writable",
    "renderBrushView": "writable",
    "renderColorMatchSub": "writable",
    "renderCostEstimator": "writable",
    "renderDilutionStrip": "writable",
    "renderHarmonyColorGrid": "writable",
    "renderHarmonyPage": "writable",
    "renderHarmonyResult": "writable",
    "renderMixBarHtml": "writable",
    "renderMixingChartSub": "writable",
    "renderMixingView": "writable",
    "renderOpacityChart": "writable",
    "renderPaletteArea": "writable",
    "renderPaletteList": "writable",
    "renderPaletteView": "writable",
    "renderPigmentCompare": "writable",
    "renderPigmentGroups": "writable",
    "renderRecipes": "writable",
    "renderRecommendedPalettes": "writable",
    "renderRef": "writable",
    "renderShopGrid": "writable",
    "renderShoppingPage": "writable",
    "renderSwatchCanvas": "writable",
    "renderSwatchView": "writable",
    "renderTracker": "writable",
    "renderTranspCanvas": "writable",
    "renderValueStudyHistogram": "writable",
    "renderValueStudyPage": "writable",
    "renderValueStudyReading": "writable",
    "renderValueStudyScaleChart": "writable",
    "renderValueStudyZoneKey": "writable",
    "renderVsAttribution": "writable",
    "renderWheelView": "writable",
    "resetMixModeState": "writable",
    "rgbToHex": "writable",
    "runColorMatch": "writable",
    "runValueStudySuggest": "writable",
    "sampleValueStudyAt": "writable",
    "saveColorNote": "writable",
    "savePaletteNotes": "writable",
    "savePalettes": "writable",
    "saveShoppingList": "writable",
    "saveTubeData": "writable",
    "selectPalette": "writable",
    "setBrushDilution": "writable",
    "setBrushSize": "writable",
    "setHarmonyRoot": "writable",
    "setHarmonyType": "writable",
    "setMixingSubView": "writable",
    "setPalSort": "writable",
    "setPaletteView": "writable",
    "setRefFromDropdown": "writable",
    "setRefLF": "writable",
    "setTubeLevel": "writable",
    "setValueStudyView": "writable",
    "setValueStudyZones": "writable",
    "shopAdd": "writable",
    "shopBrand": "writable",
    "shopClearBought": "writable",
    "shopListBrand": "writable",
    "shopRemove": "writable",
    "shopSearch": "writable",
    "shopSearchBuilt": "writable",
    "shopSetBrand": "writable",
    "shopSetListBrand": "writable",
    "shopSetNote": "writable",
    "shopToggle": "writable",
    "shoppingList": "writable",
    "showPage": "writable",
    "showRecipeSubstitute": "writable",
    "showToast": "writable",
    "swatchCamAction": "writable",
    "syncNavTabActive": "writable",
    "syncRefMobileSwitcher": "writable",
    "toggleMixMode": "writable",
    "toggleMixSelect": "writable",
    "toggleMobileDrawer": "writable",
    "toggleMobileSidebar": "writable",
    "toggleNavMore": "writable",
    "toggleSwatchPhoto": "writable",
    "trackChangeForBackupReminder": "writable",
    "triggerPhotoUpload": "writable",
    "triggerValueStudyUpload": "writable",
    "tubeData": "writable",
    "undoBrushStroke": "writable",
    "updateBackupReminderBanner": "writable",
    "updateBrushLoadedChip": "writable",
    "updateMobileBar": "writable",
    "vsCurrentAttribution": "writable",
    "vsLoadRemoteImage": "writable",
    "vsNextMasterIndex": "writable",
    "vsNextPromptIndex": "writable",
    "vsRenderPrompt": "writable",
    "vsRerollPromptCat": "writable",
    "vsResolveCommonsUrl": "writable",
    "vsRollAgain": "writable",
    "vsRollAllPrompt": "writable",
    "vsRollMaster": "writable",
    "vsRollMode": "writable",
    "vsRollPhoto": "writable",
    "vsShuffledIndices": "writable",
    "vsState": "writable",
    "vsTogglePromptCard": "writable"
};

module.exports = [
  {
    files: ["src/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "script", // NOT "module" — see note above
      globals: {
        // Browser environment
        window: "readonly", document: "readonly", navigator: "readonly",
        localStorage: "readonly", console: "readonly", fetch: "readonly",
        Image: "readonly", File: "readonly", Blob: "readonly", FileReader: "readonly",
        requestAnimationFrame: "readonly", setTimeout: "readonly", setInterval: "readonly",
        clearTimeout: "readonly", clearInterval: "readonly", performance: "readonly",
        IntersectionObserver: "readonly", Response: "readonly", URL: "readonly",
        self: "readonly", caches: "readonly",
        // This app's own cross-file globals (generated — see comment above)
        ...appGlobals
      }
    },
    rules: {
      // The big one: catches exactly the "dangling reference" bug class
      // that's shown up repeatedly in manual review passes on this app.
      "no-undef": "error",
      // Real code smell but not worth blocking a build over immediately —
      // there's a fair amount of accumulated dead code to clean up first.
      "no-unused-vars": "warn",
      // This app intentionally uses console.error for diagnostics (see
      // safeSetItem / the global error handlers in state-core.js).
      "no-console": "off",
      "no-empty": ["warn", { "allowEmptyCatch": true }]
    }
  }
];
